FROM quay.io/keycloak/keycloak:26.6.4

USER root
COPY --chmod=644 iaerp-realm.json /opt/keycloak/data/import/iaerp-realm.json
COPY --chmod=755 configure-staging.sh /opt/iaerp/configure-staging.sh
USER 1000
