"""billing sales documents and sequences

Revision ID: 57e96c2e2562
Revises: 7151caa319ac
Create Date: 2026-07-04 07:34:41.370881
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "57e96c2e2562"
down_revision: str | None = "7151caa319ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_documents",
        sa.Column("document_type", sa.String(length=20), nullable=False),
        sa.Column("establishment_id", sa.Uuid(), nullable=False),
        sa.Column("emission_point_id", sa.Uuid(), nullable=False),
        sa.Column("sequential", sa.String(length=9), nullable=False),
        sa.Column("access_key", sa.String(length=49), nullable=True),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fiscal_policy_version", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("authorization_number", sa.String(length=49), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "emission_point_id"],
            ["emission_points.tenant_id", "emission_points.id"],
            name="fk_sales_documents_tenant_emission_point",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "establishment_id"],
            ["establishments.tenant_id", "establishments.id"],
            name="fk_sales_documents_tenant_establishment",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "party_id"],
            ["parties.tenant_id", "parties.id"],
            name="fk_sales_documents_tenant_party",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_documents_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_documents")),
        sa.UniqueConstraint("access_key", name="uq_sales_documents_access_key"),
        sa.UniqueConstraint(
            "tenant_id",
            "document_type",
            "establishment_id",
            "emission_point_id",
            "sequential",
            name="uq_sales_documents_tenant_type_establishment_point_sequential",
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_sales_documents_tenant_id"),
    )
    op.create_index(
        op.f("ix_sales_documents_tenant_id"), "sales_documents", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_sales_documents_tenant_issue_date",
        "sales_documents",
        ["tenant_id", "issue_date"],
        unique=False,
    )
    op.create_index(
        "ix_sales_documents_tenant_status",
        "sales_documents",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "sequences",
        sa.Column("document_type", sa.String(length=20), nullable=False),
        sa.Column("establishment_id", sa.Uuid(), nullable=False),
        sa.Column("emission_point_id", sa.Uuid(), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "emission_point_id"],
            ["emission_points.tenant_id", "emission_points.id"],
            name="fk_sequences_tenant_emission_point",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "establishment_id"],
            ["establishments.tenant_id", "establishments.id"],
            name="fk_sequences_tenant_establishment",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sequences_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sequences")),
        sa.UniqueConstraint(
            "tenant_id",
            "document_type",
            "establishment_id",
            "emission_point_id",
            name="uq_sequences_tenant_type_establishment_point",
        ),
    )
    op.create_index(op.f("ix_sequences_tenant_id"), "sequences", ["tenant_id"], unique=False)
    op.create_table(
        "document_artifacts",
        sa.Column("sales_document_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_type", sa.String(length=20), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sales_document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_document_artifacts_tenant_sales_document",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_document_artifacts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_artifacts")),
        sa.UniqueConstraint(
            "tenant_id",
            "sales_document_id",
            "artifact_type",
            "version",
            name="uq_document_artifacts_tenant_document_type_version",
        ),
    )
    op.create_index(
        "ix_document_artifacts_document",
        "document_artifacts",
        ["tenant_id", "sales_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_artifacts_tenant_id"), "document_artifacts", ["tenant_id"], unique=False
    )
    op.create_table(
        "document_relations",
        sa.Column("credit_note_id", sa.Uuid(), nullable=False),
        sa.Column("related_invoice_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "credit_note_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_document_relations_tenant_credit_note",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "related_invoice_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_document_relations_tenant_related_invoice",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_document_relations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_relations")),
        sa.UniqueConstraint(
            "tenant_id", "credit_note_id", name="uq_document_relations_tenant_credit_note"
        ),
    )
    op.create_index(
        "ix_document_relations_related_invoice",
        "document_relations",
        ["tenant_id", "related_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relations_tenant_id"), "document_relations", ["tenant_id"], unique=False
    )
    op.create_table(
        "sales_document_lines",
        sa.Column("sales_document_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("discount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("base_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_sri_code", sa.String(length=20), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["products.tenant_id", "products.id"],
            name="fk_sales_document_lines_tenant_product",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sales_document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_sales_document_lines_tenant_sales_document",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sales_document_lines_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_document_lines")),
    )
    op.create_index(
        "ix_sales_document_lines_document",
        "sales_document_lines",
        ["tenant_id", "sales_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_document_lines_tenant_id"),
        "sales_document_lines",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "sales_document_installments",
        sa.Column("sales_document_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "amount > 0", name="ck_sales_document_installments_amount_positive"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sales_document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_sales_document_installments_tenant_sales_document",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_document_installments_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_document_installments")),
        sa.UniqueConstraint(
            "tenant_id",
            "sales_document_id",
            "sequence",
            name="uq_sales_document_installments_tenant_document_sequence",
        ),
    )
    op.create_index(
        "ix_sales_document_installments_document",
        "sales_document_installments",
        ["tenant_id", "sales_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_document_installments_tenant_id"),
        "sales_document_installments",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "sri_transmissions",
        sa.Column("sales_document_id", sa.Uuid(), nullable=False),
        sa.Column("access_key", sa.String(length=49), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("authorization_number", sa.String(length=49), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sales_document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_sri_transmissions_tenant_sales_document",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sri_transmissions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sri_transmissions")),
    )
    op.create_index(
        "ix_sri_transmissions_document",
        "sri_transmissions",
        ["tenant_id", "sales_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_sri_transmissions_access_key",
        "sri_transmissions",
        ["access_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sri_transmissions_tenant_id"), "sri_transmissions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sri_transmissions_tenant_id"), table_name="sri_transmissions")
    op.drop_index("ix_sri_transmissions_access_key", table_name="sri_transmissions")
    op.drop_index("ix_sri_transmissions_document", table_name="sri_transmissions")
    op.drop_table("sri_transmissions")
    op.drop_index(
        op.f("ix_sales_document_installments_tenant_id"),
        table_name="sales_document_installments",
    )
    op.drop_index(
        "ix_sales_document_installments_document", table_name="sales_document_installments"
    )
    op.drop_table("sales_document_installments")
    op.drop_index(
        op.f("ix_sales_document_lines_tenant_id"), table_name="sales_document_lines"
    )
    op.drop_index("ix_sales_document_lines_document", table_name="sales_document_lines")
    op.drop_table("sales_document_lines")
    op.drop_index(op.f("ix_document_relations_tenant_id"), table_name="document_relations")
    op.drop_index("ix_document_relations_related_invoice", table_name="document_relations")
    op.drop_table("document_relations")
    op.drop_index(op.f("ix_document_artifacts_tenant_id"), table_name="document_artifacts")
    op.drop_index("ix_document_artifacts_document", table_name="document_artifacts")
    op.drop_table("document_artifacts")
    op.drop_index(op.f("ix_sequences_tenant_id"), table_name="sequences")
    op.drop_table("sequences")
    op.drop_index("ix_sales_documents_tenant_status", table_name="sales_documents")
    op.drop_index("ix_sales_documents_tenant_issue_date", table_name="sales_documents")
    op.drop_index(op.f("ix_sales_documents_tenant_id"), table_name="sales_documents")
    op.drop_table("sales_documents")
    # ### end Alembic commands ###
