"""receivables cartera

Revision ID: f170c0d8901c
Revises: 57e96c2e2562
Create Date: 2026-07-05 19:35:14.458050
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f170c0d8901c"
down_revision: str | None = "57e96c2e2562"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_credits",
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("origin_credit_note_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("remaining_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "amount >= 0", name="ck_customer_credits_amount_non_negative"
        ),
        sa.CheckConstraint(
            "remaining_amount >= 0",
            name="ck_customer_credits_remaining_amount_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "origin_credit_note_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_customer_credits_tenant_origin_credit_note",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "party_id"],
            ["parties.tenant_id", "parties.id"],
            name="fk_customer_credits_tenant_party",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_customer_credits_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_credits")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_customer_credits_tenant_id"),
    )
    op.create_index(
        op.f("ix_customer_credits_tenant_id"), "customer_credits", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_customer_credits_tenant_party",
        "customer_credits",
        ["tenant_id", "party_id"],
        unique=False,
    )
    op.create_table(
        "receivables",
        sa.Column("sales_document_id", sa.Uuid(), nullable=False),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("original_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "original_amount >= 0", name="ck_receivables_original_amount_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "party_id"],
            ["parties.tenant_id", "parties.id"],
            name="fk_receivables_tenant_party",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sales_document_id"],
            ["sales_documents.tenant_id", "sales_documents.id"],
            name="fk_receivables_tenant_sales_document",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_receivables_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivables")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_receivables_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "sales_document_id", name="uq_receivables_tenant_sales_document"
        ),
    )
    op.create_index(
        op.f("ix_receivables_tenant_id"), "receivables", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_receivables_tenant_party", "receivables", ["tenant_id", "party_id"], unique=False
    )
    op.create_index(
        "ix_receivables_tenant_status", "receivables", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "receivable_installments",
        sa.Column("receivable_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "amount >= 0", name="ck_receivable_installments_amount_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receivable_id"],
            ["receivables.tenant_id", "receivables.id"],
            name="fk_receivable_installments_tenant_receivable",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_receivable_installments_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivable_installments")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_receivable_installments_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id",
            "receivable_id",
            "sequence",
            name="uq_receivable_installments_tenant_receivable_sequence",
        ),
    )
    op.create_index(
        "ix_receivable_installments_due_date",
        "receivable_installments",
        ["tenant_id", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_receivable_installments_receivable",
        "receivable_installments",
        ["tenant_id", "receivable_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receivable_installments_tenant_id"),
        "receivable_installments",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "movements",
        sa.Column("receivable_id", sa.Uuid(), nullable=False),
        sa.Column("installment_id", sa.Uuid(), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("support_reference", sa.String(length=200), nullable=True),
        sa.Column("reversed_movement_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount >= 0", name="ck_movements_amount_non_negative"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "installment_id"],
            ["receivable_installments.tenant_id", "receivable_installments.id"],
            name="fk_movements_tenant_installment",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receivable_id"],
            ["receivables.tenant_id", "receivables.id"],
            name="fk_movements_tenant_receivable",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reversed_movement_id"],
            ["movements.tenant_id", "movements.id"],
            name="fk_movements_tenant_reversed_movement",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_movements_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movements")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_movements_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "reversed_movement_id", name="uq_movements_tenant_reversed_movement"
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "installment_id",
            "movement_type",
            "support_reference",
            name="uq_movements_tenant_installment_type_reference",
        ),
    )
    op.create_index(
        "ix_movements_installment", "movements", ["tenant_id", "installment_id"], unique=False
    )
    op.create_index(
        "ix_movements_receivable", "movements", ["tenant_id", "receivable_id"], unique=False
    )
    op.create_index(
        op.f("ix_movements_tenant_id"), "movements", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movements_tenant_id"), table_name="movements")
    op.drop_index("ix_movements_receivable", table_name="movements")
    op.drop_index("ix_movements_installment", table_name="movements")
    op.drop_table("movements")
    op.drop_index(
        op.f("ix_receivable_installments_tenant_id"), table_name="receivable_installments"
    )
    op.drop_index("ix_receivable_installments_receivable", table_name="receivable_installments")
    op.drop_index("ix_receivable_installments_due_date", table_name="receivable_installments")
    op.drop_table("receivable_installments")
    op.drop_index("ix_receivables_tenant_status", table_name="receivables")
    op.drop_index("ix_receivables_tenant_party", table_name="receivables")
    op.drop_index(op.f("ix_receivables_tenant_id"), table_name="receivables")
    op.drop_table("receivables")
    op.drop_index("ix_customer_credits_tenant_party", table_name="customer_credits")
    op.drop_index(op.f("ix_customer_credits_tenant_id"), table_name="customer_credits")
    op.drop_table("customer_credits")
    # ### end Alembic commands ###
